library:
  source-dirs: src
tests:
  monthly-budget-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - monthly-budget
copyright: 2020 Nick Rotondo (rotondozer)
maintainer: nickrotondo724@gmail.com
dependencies:
- containers
- split
- base >= 4.7 && < 5
name: monthly-budget
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Nick Rotondo
github: rotondozer/monthly-budget
license: BSD3
executables:
  monthly-budget-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - monthly-budget
description: Please see the README on GitHub at <https://github.com/rotondozer/monthly-budget#readme>
